"""
Tests for the provider patient-detail / follow-up / timeline routes,
specifically the fields added by:
  - supabase/migrations/20260827110000_patient_profile_clinical_fields.sql
    (patient_profiles.condition/clinic/enrolled_at)
  - supabase/migrations/20260827111500_follow_up_action_fields.sql
    (follow_up_actions.contacted_person/follow_up_date/follow_up_time/
    assigned_to_provider_id/notify_patient/next_action_date/next_advice)

Before this file, GET /provider/patients/{id} had exactly one assertion
(in test_auth_authorization.py, covering the empty-state case only), and
POST/GET .../follow-ups and GET .../timeline had none at all. All
database access here is an in-memory fake — no Supabase or network calls.
"""

from copy import deepcopy

import pytest
from fastapi.testclient import TestClient

from app.core.security import CurrentUser, get_current_user, get_supabase_client
from app.main import app

client = TestClient(app)

PROVIDER_USER_ID = "provider-user-1"
PROVIDER_ID = "provider-1"
PROVIDER_NAME = "Dr. Anjali Silva"
OTHER_PROVIDER_ID = "provider-2"
OTHER_PROVIDER_NAME = "Nurse M. Fernando"
PATIENT_ID = "patient-1"
ALERT_ID = "alert-1"
NOW = "2026-08-27T08:00:00+00:00"


class FakeResult:
    def __init__(self, data):
        self.data = data


class FakeQuery:
    """
    Same shape as test_provider_agent_workflow.py's fake, plus neq/is_
    (patient_detail's alerts query needs neq) and insert (create_follow_up
    needs it) — the two existing fakes in this test suite each cover only
    part of what these routes call.
    """

    def __init__(self, rows):
        self._rows = rows  # live reference into FakeSupabase.tables[name]
        self._predicates = []
        self._limit = None
        self._descending = False
        self._order_column = None
        self._update_fields = None
        self._insert_row = None

    def select(self, *_args, **_kwargs):
        return self

    def eq(self, column, value):
        self._predicates.append(lambda row, c=column, v=value: row.get(c) == v)
        return self

    def neq(self, column, value):
        self._predicates.append(lambda row, c=column, v=value: row.get(c) != v)
        return self

    def in_(self, column, values):
        self._predicates.append(lambda row, c=column, vs=values: row.get(c) in vs)
        return self

    def is_(self, column, value):
        assert value == "null"
        self._predicates.append(lambda row, c=column: row.get(c) is None)
        return self

    def order(self, column, desc=False, **_kwargs):
        self._order_column = column
        self._descending = desc
        return self

    def limit(self, value):
        self._limit = value
        return self

    def update(self, fields):
        self._update_fields = fields
        return self

    def insert(self, fields):
        # Mirrors follow_up_actions' real schema defaults (id/created_at
        # generated by Postgres) — the fake has to fill these in itself
        # since nothing here talks to a real database.
        row = {
            "id": f"generated-{len(self._rows) + 1}",
            "created_at": NOW,
            **fields,
        }
        self._insert_row = row
        return self

    def execute(self):
        if self._insert_row is not None:
            self._rows.append(self._insert_row)
            return FakeResult([deepcopy(self._insert_row)])
        matched = [row for row in self._rows if all(p(row) for p in self._predicates)]
        if self._update_fields is not None:
            for row in matched:
                row.update(self._update_fields)
        if self._order_column is not None:
            matched.sort(
                key=lambda row: row.get(self._order_column) or "",
                reverse=self._descending,
            )
        if self._limit is not None:
            matched = matched[: self._limit]
        return FakeResult([deepcopy(row) for row in matched])


class FakeSupabase:
    def __init__(self, tables):
        self.tables = deepcopy(tables)

    def table(self, name):
        return FakeQuery(self.tables.setdefault(name, []))


def _user(role="provider", user_id=PROVIDER_USER_ID):
    return CurrentUser(id=user_id, email="provider@example.com", role=role, is_active=True)


def _authorize(fake, role="provider"):
    app.dependency_overrides[get_current_user] = lambda: _user(role=role)
    app.dependency_overrides[get_supabase_client] = lambda: fake


@pytest.fixture(autouse=True)
def _clear_overrides():
    yield
    app.dependency_overrides.clear()


def _base_tables(*, follow_ups=None):
    return {
        "provider_profiles": [
            {"id": PROVIDER_ID, "user_id": PROVIDER_USER_ID, "full_name": PROVIDER_NAME},
            {"id": OTHER_PROVIDER_ID, "user_id": "other-user", "full_name": OTHER_PROVIDER_NAME},
        ],
        "patient_provider_assignments": [
            {
                "id": "assignment-1",
                "provider_id": PROVIDER_ID,
                "patient_id": PATIENT_ID,
                "is_active": True,
                "assigned_at": NOW,
            }
        ],
        "patient_profiles": [
            {
                "id": PATIENT_ID,
                "full_name": "Nimal Perera",
                "age": 62,
                "contact_number": "+94771234567",
                "condition": "Hypertension",
                "clinic": "Colombo Cardiac",
                "enrolled_at": "2026-01-28T00:00:00+00:00",
            }
        ],
        "medication_schedules": [],
        "blood_pressure_readings": [],
        "weekly_check_ins": [],
        "risk_assessments": [],
        "risk_reasons": [],
        "alerts": [
            {
                "id": ALERT_ID,
                "patient_id": PATIENT_ID,
                "status": "open",
                "risk_assessment_id": "assessment-1",
                "created_at": NOW,
                "acknowledged_at": None,
                "acknowledged_by": None,
            }
        ],
        "follow_up_actions": follow_ups if follow_ups is not None else [],
    }


def _follow_up_row(**overrides):
    row = {
        "id": "follow-up-1",
        "alert_id": ALERT_ID,
        "provider_id": PROVIDER_ID,
        "action_type": "phone_call",
        "note_text": "Spoke with patient by phone.",
        "next_advice": "Continue current medicines.",
        "outcome": "contacted",
        "status": "in_progress",
        "contacted_person": "Patient",
        "follow_up_date": "2026-08-20",
        "follow_up_time": "11:20:00",
        "assigned_to_provider_id": OTHER_PROVIDER_ID,
        "notify_patient": True,
        "next_action_date": "2026-08-27",
        "created_at": NOW,
    }
    row.update(overrides)
    return row


# --- GET /provider/patients/{id} -------------------------------------------


def test_patient_detail_includes_clinical_profile_fields_and_assigned_provider():
    fake = FakeSupabase(_base_tables())
    _authorize(fake)

    response = client.get(f"/provider/patients/{PATIENT_ID}")

    assert response.status_code == 200
    profile = response.json()["profile"]
    assert profile["condition"] == "Hypertension"
    assert profile["clinic"] == "Colombo Cardiac"
    assert profile["enrolled_at"] is not None
    assert response.json()["assigned_provider_name"] == PROVIDER_NAME


def test_patient_detail_follow_ups_carry_provider_names():
    fake = FakeSupabase(_base_tables(follow_ups=[_follow_up_row()]))
    _authorize(fake)

    response = client.get(f"/provider/patients/{PATIENT_ID}")

    assert response.status_code == 200
    follow_up = response.json()["follow_ups"][0]
    assert follow_up["provider_full_name"] == PROVIDER_NAME
    assert follow_up["assigned_to_provider_name"] == OTHER_PROVIDER_NAME
    assert follow_up["next_advice"] == "Continue current medicines."
    assert follow_up["next_action_date"] == "2026-08-27"
    assert follow_up["contacted_person"] == "Patient"
    assert follow_up["notify_patient"] is True


# --- GET /provider/patients/{id}/follow-ups --------------------------------


def test_list_follow_ups_attaches_provider_names():
    fake = FakeSupabase(_base_tables(follow_ups=[_follow_up_row()]))
    _authorize(fake)

    response = client.get(f"/provider/patients/{PATIENT_ID}/follow-ups")

    assert response.status_code == 200
    body = response.json()
    assert len(body) == 1
    assert body[0]["provider_full_name"] == PROVIDER_NAME
    assert body[0]["assigned_to_provider_name"] == OTHER_PROVIDER_NAME


# --- POST /provider/patients/{id}/follow-ups -------------------------------


def test_create_follow_up_persists_and_returns_new_fields():
    fake = FakeSupabase(_base_tables())
    _authorize(fake)

    response = client.post(
        f"/provider/patients/{PATIENT_ID}/follow-ups",
        json={
            "alert_id": ALERT_ID,
            "action_type": "phone_call",
            "note_text": "Spoke with patient by phone.",
            "next_advice": "Continue current medicines, record BP daily.",
            "outcome": "contacted",
            "status": "in_progress",
            "alert_status": "resolved",
            "contacted_person": "Patient",
            "follow_up_date": "2026-08-20",
            "follow_up_time": "11:20:00",
            "assigned_to_provider_id": OTHER_PROVIDER_ID,
            "notify_patient": True,
            "next_action_date": "2026-08-27",
        },
    )

    assert response.status_code == 201
    body = response.json()
    assert body["next_advice"] == "Continue current medicines, record BP daily."
    assert body["contacted_person"] == "Patient"
    assert body["follow_up_date"] == "2026-08-20"
    assert body["follow_up_time"] == "11:20:00"
    assert body["assigned_to_provider_id"] == OTHER_PROVIDER_ID
    assert body["assigned_to_provider_name"] == OTHER_PROVIDER_NAME
    assert body["notify_patient"] is True
    assert body["next_action_date"] == "2026-08-27"
    # The recording provider is whoever is authenticated, not
    # assigned_to_provider_id — confirms these two names don't get mixed up.
    assert body["provider_full_name"] == PROVIDER_NAME

    # Existing side effect (predates this migration) must still work: the
    # alert itself is resolved, not just the follow_up_actions row.
    assert fake.tables["alerts"][0]["status"] == "resolved"


def test_create_follow_up_without_optional_new_fields_still_succeeds():
    """None of the new fields are required — a minimal request (the old
    shape) must keep working exactly as before this migration."""
    fake = FakeSupabase(_base_tables())
    _authorize(fake)

    response = client.post(
        f"/provider/patients/{PATIENT_ID}/follow-ups",
        json={
            "alert_id": ALERT_ID,
            "action_type": "note",
            "note_text": "Left a voicemail.",
        },
    )

    assert response.status_code == 201
    body = response.json()
    assert body["next_advice"] is None
    assert body["contacted_person"] is None
    assert body["assigned_to_provider_id"] is None
    assert body["assigned_to_provider_name"] is None
    assert body["notify_patient"] is False
    assert body["next_action_date"] is None


def test_unassigned_provider_cannot_create_follow_up():
    tables = _base_tables()
    tables["patient_provider_assignments"] = []
    fake = FakeSupabase(tables)
    _authorize(fake)

    response = client.post(
        f"/provider/patients/{PATIENT_ID}/follow-ups",
        json={"alert_id": ALERT_ID, "action_type": "note", "note_text": "x"},
    )
    assert response.status_code == 404


# --- GET /provider/patients/{id}/timeline ----------------------------------


def test_timeline_follow_up_entry_includes_provider_name():
    fake = FakeSupabase(_base_tables(follow_ups=[_follow_up_row()]))
    _authorize(fake)

    response = client.get(f"/provider/patients/{PATIENT_ID}/timeline")

    assert response.status_code == 200
    entries = response.json()
    follow_up_entries = [e for e in entries if e["entry_type"] == "follow_up"]
    assert len(follow_up_entries) == 1
    assert follow_up_entries[0]["data"]["provider_full_name"] == PROVIDER_NAME
    assert follow_up_entries[0]["data"]["next_action_date"] == "2026-08-27"
